
/*CALCOLO DEL PI GRECO ATTRAVERSO LA FORMULA DI MADHAVA-LEIBNIZ CON NUMERO DI APPROSSIMAZIONI INSERITE DALL'UTENTE*/
/*BAVARO VITO A-L*/

#include<stdio.h>
int main() {
	int appro; /*NUMERO DI APPROSSIMAZIONI DA SEGUIRE*/
	int contatore = 0;            
	int n = 1;
	float pi = 1;
	
	printf("CALCOLO DEL PIGRECO\n");
	printf("Inserisci il numero di approssimazioni da eseguire:");
	scanf_s("%d", &appro); /*INSERIRE I NUMERO DI APPROSSIMAZIONI DA ESEGUIRE*/
	
	while (contatore != appro){ /*CICLA FINCHE IL CONTATORE (INIZIALIZZATO A 0) NON E' PARI AL NUMERO DI APPROSSIMAZIONI INSERITE DALL'UTENTE*/
		if (n % 2 == 0) { /*VERIFICA SE IL RESTO DELLA DIVISIONE DI N (INIZIALIZZATO A 1) E' 0 (QUINDI PARI)*/
			pi += 1 /(2 * (float) n + 1); /*ESEGUI LA FOMULA CON SEGNO + (APPLICA IL CASTING)*/
			n += 1; /*INCREMENTA N*/
			contatore += 1; /*INCREMENTA CONTATORE*/
		}
		else { /*SE IL RESTO E' UGUALE A 1 (QUINDI DISPARI)*/
			pi -= 1 / (2 * (float) n + 1); /*ESEGUI LA FORMULA CON SEGNO - (APPLICA IL CASTING)*/
			n += 1; /*INCREMENTA N*/
			contatore += 1; /*INCREMENTA CONTATORE*/
		}
	}
	
	printf("Il pigreca quarti approssimato e': ");
	printf("%f\n", pi); /*STAMPA UN QUARTO PIGRECO*/
	pi = pi * 4; /*CALCOLA PIGRECO*/
	printf("Il pigreco approssimato e': ");
	printf("%f", pi); /*STAMPA PIGRECO*/
	return 0;
}

/*DOMANDA 1: 300 VOLTE PER LA SECONDA CIFRA,300000 VOLTE PER LA QUARTA CIFRA*/
/*DOMANDA 2: SI, SI PUO IMPLEMENTARE LA STESSA FORMULA ALTERNANDO LE SOMME E LE DIFFERENZE SEMPLICEMENTE VERIFICANDO SE N (OGNI VOLTA INCREMENTATO DI 1 E INIZIALIZZATO A 1) è PARI O DISPARI, SE PARI IL -1 DELLA FORMULA CAMBIA SEGNO, IN CASO CONTRARIO IL -1 MANTIENE IL SEGNO*/
/*DOMANDO 3: VIENE ESEGUITA UNA VOLTA IN MENO*/